package com.thehbc.bilimusic.ui.theme

import androidx.compose.ui.graphics.Color

// ── B站品牌主色 ──────────────────────────────────────────────────────────────
val BiliPink       = Color(0xFFFB7299)
val BiliPinkLight  = Color(0xFFFF94B4)
val BiliPinkDark   = Color(0xFFC85B7A)

// ── Light 色彩体系（基于 BiliPink seed 的 MD3 生成结果）────────────────────
val md_theme_light_primary            = Color(0xFFBE1558)
val md_theme_light_onPrimary          = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer   = Color(0xFFFFD9E3)
val md_theme_light_onPrimaryContainer = Color(0xFF3F0017)
val md_theme_light_secondary          = Color(0xFF74565C)
val md_theme_light_onSecondary        = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E0)
val md_theme_light_onSecondaryContainer = Color(0xFF2C1519)
val md_theme_light_tertiary           = Color(0xFF7A5635)
val md_theme_light_onTertiary         = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer  = Color(0xFFFFDCBD)
val md_theme_light_onTertiaryContainer = Color(0xFF2D1600)
val md_theme_light_error              = Color(0xFFBA1A1A)
val md_theme_light_onError            = Color(0xFFFFFFFF)
val md_theme_light_errorContainer     = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer   = Color(0xFF410002)
val md_theme_light_background         = Color(0xFFFFFBFF)
val md_theme_light_onBackground       = Color(0xFF201A1B)
val md_theme_light_surface            = Color(0xFFFFFBFF)
val md_theme_light_onSurface          = Color(0xFF201A1B)
val md_theme_light_surfaceVariant     = Color(0xFFF4DDE1)
val md_theme_light_onSurfaceVariant   = Color(0xFF52363B)
val md_theme_light_outline            = Color(0xFF857375)
val md_theme_light_outlineVariant     = Color(0xFFD7C2C5)
val md_theme_light_inverseSurface     = Color(0xFF352F30)
val md_theme_light_inverseOnSurface   = Color(0xFFFAEEEF)
val md_theme_light_inversePrimary     = Color(0xFFFFB1C2)
val md_theme_light_surfaceTint        = Color(0xFFBE1558)

// ── Dark 色彩体系 ────────────────────────────────────────────────────────────
val md_theme_dark_primary             = Color(0xFFFFB1C2)
val md_theme_dark_onPrimary           = Color(0xFF670028)
val md_theme_dark_primaryContainer    = Color(0xFF93003D)
val md_theme_dark_onPrimaryContainer  = Color(0xFFFFD9E3)
val md_theme_dark_secondary           = Color(0xFFE4BEC3)
val md_theme_dark_onSecondary         = Color(0xFF43292D)
val md_theme_dark_secondaryContainer  = Color(0xFF5B3F43)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E0)
val md_theme_dark_tertiary            = Color(0xFFF1BB8D)
val md_theme_dark_onTertiary          = Color(0xFF472A0B)
val md_theme_dark_tertiaryContainer   = Color(0xFF61401F)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCBD)
val md_theme_dark_error               = Color(0xFFFFB4AB)
val md_theme_dark_onError             = Color(0xFF690005)
val md_theme_dark_errorContainer      = Color(0xFF93000A)
val md_theme_dark_onErrorContainer    = Color(0xFFFFDAD6)
val md_theme_dark_background          = Color(0xFF201A1B)
val md_theme_dark_onBackground        = Color(0xFFEBE0E1)
val md_theme_dark_surface             = Color(0xFF201A1B)
val md_theme_dark_onSurface           = Color(0xFFEBE0E1)
val md_theme_dark_surfaceVariant      = Color(0xFF52363B)
val md_theme_dark_onSurfaceVariant    = Color(0xFFD8BFC2)
val md_theme_dark_outline             = Color(0xFFA08C8F)
val md_theme_dark_outlineVariant      = Color(0xFF52363B)
val md_theme_dark_inverseSurface      = Color(0xFFEBE0E1)
val md_theme_dark_inverseOnSurface    = Color(0xFF352F30)
val md_theme_dark_inversePrimary      = Color(0xFFBE1558)
val md_theme_dark_surfaceTint         = Color(0xFFFFB1C2)